// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRSAdnnwekbhacZWQ8xRz1Qka9YAs-fs',
    appId: '1:335681675202:web:6a3131853c6aad3a5f805b',
    messagingSenderId: '335681675202',
    projectId: 'proyecto-3c7e7',
    authDomain: 'proyecto-3c7e7.firebaseapp.com',
    storageBucket: 'proyecto-3c7e7.appspot.com',
    measurementId: 'G-T1P7QMH3TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClFvGezHXfvzPctooXBO1HAdGw4kYx9rg',
    appId: '1:335681675202:android:420952d0c3a13f845f805b',
    messagingSenderId: '335681675202',
    projectId: 'proyecto-3c7e7',
    storageBucket: 'proyecto-3c7e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_KArUH0-ZMJJ8NJcBt5jCQGm6ToWqPiA',
    appId: '1:335681675202:ios:964b2a0f9935e2595f805b',
    messagingSenderId: '335681675202',
    projectId: 'proyecto-3c7e7',
    storageBucket: 'proyecto-3c7e7.appspot.com',
    iosBundleId: 'com.example.proyecto',
  );
}
